# LOCATION: backend/make_samples.py  (next to manage.py and ml_models/; writes samples.ts)
"""Run from the backend folder: python make_samples.py
Writes src/data/samples.ts with one REAL record per class, taken from the dataset
you trained on (cicids2017_preprocessed.csv), for the 'Load sample' dropdown."""
import json, joblib, numpy as np, pandas as pd
df = pd.read_csv('cicids2017_preprocessed.csv')
fn = joblib.load('ml_models/feature_names.pkl')
out = []
for label, g in df.groupby('Label'):
    if label == 'Infiltration':
        continue  # only 36 rows in the dataset
    row = g.sample(1, random_state=7).iloc[0]
    feats = {k: float(row[k]) for k in fn if np.isfinite(row[k])}
    out.append({'label': str(label), 'features': feats})
ts = "// Auto-generated by make_samples.py. Real CICIDS2017 records.\n"
ts += "export interface Sample { label: string; features: Record<string, number>; }\n"
ts += "export const SAMPLES: Sample[] = " + json.dumps(out) + ";\n"
open('samples.ts', 'w').write(ts)
print('wrote samples.ts', [o['label'] for o in out])