# Generated by Django 6.1.1 on 2026-10-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='threats.threat'),
        ),
    ]
