# Generated by Django 6.1.1 on 2026-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Minimum confidence (0.0-1.0) to flag as a threat')),
                ('critical_threshold', models.FloatField(default=0.95, help_text='Confidence above this = CRITICAL severity')),
                ('high_threshold', models.FloatField(default=0.85, help_text='Confidence above this = HIGH severity')),
                ('medium_threshold', models.FloatField(default=0.7, help_text='Confidence above this = MEDIUM severity, below = LOW')),
                ('auto_create_incidents', models.BooleanField(default=True, help_text='Automatically create incidents when threats are detected')),
                ('auto_create_alerts', models.BooleanField(default=True, help_text='Automatically create alerts when threats are detected')),
                ('websocket_notifications', models.BooleanField(default=True, help_text='Enable real-time WebSocket notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
