# Generated by Django 6.1.1 on 2026-09-10 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_features', models.JSONField(blank=True, null=True)),
                ('shap_explanation', models.JSONField(blank=True, null=True)),
                ('lime_explanation', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
